### ISSUE TITLE
[Feat] 친구 리스트 뷰, 응원하기 뷰 API 연동 (1)

### ISSUE THREAD

**Issue by kpk0616** [SOPT-31st-SOPKATHON-12/SOPKATHON-iOS#19]
## 🛠 Issue
- 친구 리스트 뷰 및 응원하기 뷰 API 연동

## 📝 To-do
- [x] 친구 리스트 뷰 API 연동: 서버의 친구 리스트 불러온 후 테이블뷰에 적용
- [x] 응원하기 뷰 API 연동: 친구 스토리 뷰의 친구 이름 변경
- [ ] 응원하기 뷰 API 연동: 친구 스토리 뷰의 시간 변경
- [ ] 응원하기 뷰 API 연동: 응원하기 여부 (힘주기 / 힘주기 완료) 적용
